### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ghost** [FailedShack/USBHelperInstaller#12]
Just wondering if this had Linux Wine support. If not I'll take a crack at recoding it in Python (:

**Comment by SpaghettDev** [comment]
afaik this software is no longer gonna be updated by FailedShak

**Comment by ghost** [comment]
> afaik this software is no longer gonna be updated by FailedShak

I know that, was just wondering if the source can be compiled to Linux

**Comment by IFoodstampZ** [comment]
no hurt in trying, just git clone and makepkg

**Comment by BubbyNX** [comment]
Any progress on this end?  I installed through WINE and I'm getting the following error whenever I try to launch the program (after successful installation) : https://api.nul.sh/logs/F9kwWoZx4Kj4

**Comment by ghost** [comment]
> Any progress on this end? I installed through WINE and I'm getting the following error whenever I try to launch the program (after successful installation) : https://api.nul.sh/logs/F9kwWoZx4Kj4

No there's been no progress in running it on Linux. However I found Python adaptations that do the same thing. I have one that's been heavily edited by me in my github repos if you'd like to check it out, It's a GUI adaptation of the original FunKiiU script. While someone else made the main code I compiled the scripts into one GUI.py and edited much of the download process.

**Comment by lpuv** [comment]
@Korozin thanks for your FunKitGui!

**Comment by BubbyNX** [comment]
> > Any progress on this end? I installed through WINE and I'm getting the following error whenever I try to launch the program (after successful installation) : https://api.nul.sh/logs/F9kwWoZx4Kj4
> 
> No there's been no progress in running it on Linux. However I found Python adaptations that do the same thing. I have one that's been heavily edited by me in my github repos if you'd like to check it out, It's a GUI adaptation of the original FunKiiU script. While someone else made the main code I compiled the scripts into one GUI.py and edited much of the download process.

thanks! I’ll check it out. For some reason I didn’t see this reply until today haha

**Comment by ghost** [comment]
> > > Any progress on this end? I installed through WINE and I'm getting the following error whenever I try to launch the program (after successful installation) : https://api.nul.sh/logs/F9kwWoZx4Kj4
> > 
> > 
> > No there's been no progress in running it on Linux. However I found Python adaptations that do the same thing. I have one that's been heavily edited by me in my github repos if you'd like to check it out, It's a GUI adaptation of the original FunKiiU script. While someone else made the main code I compiled the scripts into one GUI.py and edited much of the download process.
> 
> thanks! I’ll check it out. For some reason I didn’t see this reply until today haha

Dw about it. The script might now be a bit iffy / out of date. But if you have any problems, lmk. I can link to working alternatives.
