### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by 0megaplus** [FailedShack/USBHelperInstaller#19]
I scanned the .exe file with VirusTotal, and three malware files were found.

Is this safe? Or is this just some other issue? 
I want to make sure before I install this.

Please make a truthful answer, and **verify** it's not a virus.

Thanks, Omega207

I'm using the latest release on GitHub.

**Comment by Masamune3210** [comment]
About a million people use USB Helper daily, don't you think that if it were malicious in any way people would be talking about it?
Anti-malware is horrendous at false positives with projects like this, about half of github would set off their scanners if you tried.

**Comment by 0megaplus** [comment]
Good point. Sorry, that was ridiculous of me.
