### ISSUE TITLE
503 server code

### ISSUE THREAD

**Issue by Volnetiks** [FailedShack/USBHelperInstaller#2]
Hello, i just download the usbinstaller, and when i agree the term, i got an error: "Could not establish a connection.
Please check your internet connection and try again.
Reason: Server Error (503)"
I restarted my box a few minutes ago, and, i still got this error, but i can watch video or streams, so, i dont think it came from my connection, any idea?

**Comment by simonj0** [comment]
The installer downloads files from archive.org, which is currently not available (see [https://twitter.com/internetarchive/status/1143378990826004480](https://twitter.com/internetarchive/status/1143378990826004480)).
You can either wait until it's back up, or install the program manually by extracting [USBHelperLauncher](https://github.com/FailedShack/USBHelperLauncher/releases/latest) and [Wii U USB Helper](https://mega.nz/#!pNYVESxD!fxn0dS4hSihstG-OOJz9gaUJCS5UmVPimmMBED7-POs) into the same directory and running `USBHelperLauncher.exe`.

**Comment by Volnetiks** [comment]
It works, thanks

**Comment by FailedShack** [comment]
9d17650b384d73246e2143d197e84ddf1cdffd79 should prevent this from happening again.
