### ISSUE TITLE
gamecube iso file error code with server

### ISSUE THREAD

**Issue by Solipund** [FailedShack/USBHelperInstaller#21]
Getting a 404 server error code when I upload a gamecube iso file into the converter. 
as seen below. 
ive tried to reinstall usb helper, along with switching the title keys etc. still no luck. 

![issu](https://user-images.githubusercontent.com/109878756/180624509-f376374e-67ee-4c31-8e02-2ab3831e91ab.PNG)

**Comment by Masamune3210** [comment]
You aren't uploading anything, just selecting it. Make sure the paths to both your iso and the location you are trying to write your games to isn't too long, as Windows has problems with long folder paths over a certain length

**Comment by Solipund** [comment]
ive moved both paths up so they werent long. Still getting the error

**Comment by crimsonnight** [comment]
I'm also having this issue - I've tried with different games and ISO to confirm

**Comment by blawdi** [comment]
Same error with wii

**Comment by FailedShack** [comment]
Server issue should have been resolved. Ask to reopen if error persists.
