### ISSUE TITLE
MKWii fails to patch with wiimfi

### ISSUE THREAD

**Issue by thanone2** [FailedShack/USBHelperInstaller#35]
![image](https://github.com/user-attachments/assets/b141d6de-44b4-43ea-a331-920c599da980)
![image](https://github.com/user-attachments/assets/184d14fb-a4a8-4208-81bb-e632396b4197)

**Comment by Masamune3210** [comment]
A. This has nothing to do with USB Helper
B. The picture you posted is quite literally telling you what the problem is....multiple times over.

**Comment by thanone2** [comment]
> A. This has nothing to do with USB Helper B. The picture you posted is quite literally telling you what the problem is....multiple times over.

hold on, lemme get the original error that led me to this point

**Comment by thanone2** [comment]
![image](https://github.com/user-attachments/assets/91257686-4600-4dea-9583-da7c0ad53cc9)
there is no folder called "wiimmfi-images"
I'm injecting this for my WiiU so I can use the pro controller, if there's a better way, pls go ahead and tell me

**Comment by Masamune3210** [comment]
Don't use the patchers in USB Helper, half of them don't work correctly anymore and the half that do take way more effort than they should to get them into a workable state.

**Comment by thanone2** [comment]
> Don't use the patchers in USB Helper, half of them don't work correctly anymore and the half that do take way more effort than they should to get them into a workable state.

is there a better way to patch mkwii to use my gamepad and pro controller?

**Comment by thanone2** [comment]
nvm I found a way

**Comment by Gaminguide1000** [comment]
> nvm I found a way

Well what the hell is the solution
